### ISSUE TITLE
Please add licence file

### ISSUE THREAD

**Issue by ohinder** [srafiei95/GPU-enabled-Gradient-Based-DCOPF#1]
Hello,

I would like to play around with your code but there is no license file. See:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Could you add a license, e.g., https://opensource.org/license/mit

Thanks!

**Comment by srafiei95** [comment]
Hi Dr. Hinder,
Thank you for your interest in my code! I have added the MIT license as requested. Please feel free to reach out if you have any questions or need assistance with any aspect of the code. I'm more than happy to help and learn from your feedback!
Best regards,
Saba

From: Oliver Hinder ***@***.***>
Date: Tuesday, July 9, 2024 at 10:11 AM
To: srafiei95/GPU-enabled-Gradient-Based-DCOPF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [srafiei95/GPU-enabled-Gradient-Based-DCOPF] Please add licence file (Issue #1)

Hello,

I would like to play around with your code but there is no license file. See:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Could you add a license, e.g., https://opensource.org/license/mit

Thanks!

**Comment by ohinder** [comment]
Thank you!
